### ISSUE TITLE
logfile not created during setup, systemd service setup as system wide

### ISSUE THREAD

**Issue by mh-cbon** [wmhilton/hypergit-service#1]
## logfile not created during setup

tldr;

```sh
[mh-cbon@pc2 ~] $ /home/mh-cbon/.nvm/versions/node/v10.4.0/bin/node /home/mh-cbon/.nvm/versions/node/v10.4.0/bin/hypergit-service seed
[2018-7-3 13:07:23] Running with CLI arguments: /home/mh-cbon/.nvm/versions/node/v10.4.0/bin/node /home/mh-cbon/.nvm/versions/node/v10.4.0/bin/hypergit-service seed
fs.js:145
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/mh-cbon/.local/state/hypergit-nodejs/log.txt'
    at Object.fs.openSync (fs.js:579:3)
    at Object.fs.writeFileSync (fs.js:1309:33)
    at Object.fs.appendFileSync (fs.js:1355:6)
    at Console.args [as log] (/home/mh-cbon/.nvm/versions/node/v10.4.0/lib/node_modules/hypergit-service/node_modules/console2file/lib/index.js:111:20)
    at fs.unlink (/home/mh-cbon/.nvm/versions/node/v10.4.0/lib/node_modules/hypergit-service/bin/cli.js:82:19)
    at FSReqWrap.oncomplete (fs.js:171:20)
```

solution;

```sh
[mh-cbon@pc2 ~] $ mkdir -p /home/mh-cbon/.local/state/hypergit-nodejs/ 
[mh-cbon@pc2 ~] $ /home/mh-cbon/.nvm/versions/node/v10.4.0/bin/node /home/mh-cbon/.nvm/versions/node/v10.4.0/bin/hypergit-service seed
[2018-7-3 13:11:03] Running with CLI arguments: /home/mh-cbon/.nvm/versions/node/v10.4.0/bin/node /home/mh-cbon/.nvm/versions/node/v10.4.0/bin/hypergit-service seed
[2018-7-3 13:11:03] [207dbaef657d688ad528573ae66b5a0bede40fcb82e6b91afc44ddd43c84874f] seeding
[2018-7-3 13:11:03] [5701a1c08ae15dba17e181b1a9a28bdfb8b95200d77a25be6051bb018e25439a] seeding
[2018-7-3 13:11:04] (node:17305) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
[2018-7-3 13:11:04] [207dbaef657d688ad528573ae66b5a0bede40fcb82e6b91afc44ddd43c84874f] found peer 60d2fcab2a2b7105e7131fcb52fa475d93906294e877e8d8c5508e67b3bb6159
^C[mh-cbon@pc2 ~] $ 
```

## systemd service setup as system wide

at least on this distro (fedora 28) the service finally created can not work for now.

The service definition is setup into /lib/systemd/system, which is like root services.

So when starting it up, it fails for permissions/whatever/ issues around the log file (and maybe more things i have not tested).

solution;

for now i worked around by forcing user/group into the service definition.

```sh
[mh-cbon@pc2 ~] $ cat /lib/systemd/system/hypergit-service.service 
[Unit]
Description=hypergit-service
After=network.target
Requires=

[Service]
Type=simple
StandardOutput=null
StandardError=null
UMask=0007
ExecStart=/home/mh-cbon/.nvm/versions/node/v10.4.0/bin/node  /home/mh-cbon/.nvm/versions/node/v10.4.0/bin/hypergit-service "seed"
User=mh-cbon
Group=mh-cbon

[Install]
WantedBy=multi-user.target
$ sudo systemctl daemon-reload
[mh-cbon@pc2 ~] $ sudo systemctl restart hypergit-service.service
[mh-cbon@pc2 ~] $ sudo systemctl status hypergit-service.service
● hypergit-service.service - hypergit-service
   Loaded: loaded (/usr/lib/systemd/system/hypergit-service.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2018-07-03 13:18:47 CEST; 4s ago
 Main PID: 18834 (node)
    Tasks: 10 (limit: 4915)
   Memory: 36.7M
   CGroup: /system.slice/hypergit-service.service
           └─18834 /home/mh-cbon/.nvm/versions/node/v10.4.0/bin/node /home/mh-cbon/.nvm/versions/node/v10.4.0/bin/hypergit-service seed

juil. 03 13:18:47 pc2.home systemd[1]: Started hypergit-service.

```

## debug

```sh
[mh-cbon@pc2 ~] $ npm i -g hypergit-service
/home/mh-cbon/.nvm/versions/node/v10.4.0/bin/hypergit-service -> /home/mh-cbon/.nvm/versions/node/v10.4.0/lib/node_modules/hypergit-service/bin/cli.js

> os-service@2.1.3 install /home/mh-cbon/.nvm/versions/node/v10.4.0/lib/node_modules/hypergit-service/node_modules/os-service
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make : on entre dans le répertoire « /home/mh-cbon/.nvm/versions/node/v10.4.0/lib/node_modules/hypergit-service/node_modules/os-service/build »
  SOLINK_MODULE(target) Release/obj.target/service.node
  COPY Release/service.node
make : on quitte le répertoire « /home/mh-cbon/.nvm/versions/node/v10.4.0/lib/node_modules/hypergit-service/node_modules/os-service/build »
npm WARN hypergit-service@0.0.1 requires a peer of hypergit@^3.2.0 but none is installed. You must install peer dependencies yourself.

+ hypergit-service@0.0.1
added 28 packages from 22 contributors in 10.383s
[mh-cbon@pc2 ~] $ npm i -g hypergit
/home/mh-cbon/.nvm/versions/node/v10.4.0/bin/hypergit -> /home/mh-cbon/.nvm/versions/node/v10.4.0/lib/node_modules/hypergit/bin/cli.js
/home/mh-cbon/.nvm/versions/node/v10.4.0/bin/git-remote-hypergit -> /home/mh-cbon/.nvm/versions/node/v10.4.0/lib/node_modules/hypergit/node_modules/.bin/git-remote-hypergit
+ hypergit@3.2.0
added 3 packages from 2 contributors and updated 7 packages in 29.688s
[mh-cbon@pc2 ~] $ hypergit-service install
installed

[mh-cbon@pc2 ~] $ ps aux | grep node
root       851  0.0  0.0   7056  1800 ?        Ss   08:22   0:00 /usr/sbin/mcelog --ignorenodev --daemon --foreground
mh-cbon  16001  0.0  0.0 213800  1080 pts/0    S+   13:04   0:00 grep --color=auto node
[mh-cbon@pc2 ~] $ ps aux | grep hyper
mh-cbon  16024  0.0  0.0 213800   960 pts/0    S+   13:05   0:00 grep --color=auto hyper
[mh-cbon@pc2 ~] $ cd $(hypergit-service logdir)
bash: cd: /home/mh-cbon/.local/state/hypergit-nodejs: No such file or directory    
[mh-cbon@pc2 ~] $ sudo systemctl status hypergit-service.service 
[sudo] Mot de passe de mh-cbon : 
● hypergit-service.service - hypergit-service
   Loaded: loaded (/usr/lib/systemd/system/hypergit-service.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
[mh-cbon@pc2 ~] $ sudo systemctl start hypergit-service.service 
[mh-cbon@pc2 ~] $ sudo systemctl status hypergit-service.service 
● hypergit-service.service - hypergit-service
   Loaded: loaded (/usr/lib/systemd/system/hypergit-service.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2018-07-03 13:06:08 CEST; 2s ago
  Process: 16291 ExecStart=/home/mh-cbon/.nvm/versions/node/v10.4.0/bin/node /home/mh-cbon/.nvm/versions/node/v10>
 Main PID: 16291 (code=exited, status=1/FAILURE)

juil. 03 13:06:07 pc2.home systemd[1]: Started hypergit-service.
juil. 03 13:06:08 pc2.home systemd[1]: hypergit-service.service: Main process exited, code=exited, status=1/FAILU>
juil. 03 13:06:08 pc2.home systemd[1]: hypergit-service.service: Failed with result 'exit-code'.
lines 1-9/9 (END)
[mh-cbon@pc2 ~] $ sudo journalctl -felu hypergit-service
-- Logs begin at Tue 2018-05-01 22:05:58 CEST. --
juil. 03 13:06:07 pc2.home systemd[1]: Started hypergit-service.
juil. 03 13:06:08 pc2.home systemd[1]: hypergit-service.service: Main process exited, code=exited, status=1/FAILURE
juil. 03 13:06:08 pc2.home systemd[1]: hypergit-service.service: Failed with result 'exit-code'.
^C
[mh-cbon@pc2 ~] $ sudo journalctl -n 50 -felu hypergit-service
-- Logs begin at Tue 2018-05-01 22:05:58 CEST. --
juil. 03 13:06:07 pc2.home systemd[1]: Started hypergit-service.
juil. 03 13:06:08 pc2.home systemd[1]: hypergit-service.service: Main process exited, code=exited, status=1/FAILURE
juil. 03 13:06:08 pc2.home systemd[1]: hypergit-service.service: Failed with result 'exit-code'.
^C
[mh-cbon@pc2 ~] $ sudo systemctl status hypergit-service.service 
● hypergit-service.service - hypergit-service
   Loaded: loaded (/usr/lib/systemd/system/hypergit-service.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2018-07-03 13:06:08 CEST; 1min 3s ago
  Process: 16291 ExecStart=/home/mh-cbon/.nvm/versions/node/v10.4.0/bin/node /home/mh-cbon/.nvm/versions/node/v10.4.0/bin/hypergit-service seed (code=exited, statu>
 Main PID: 16291 (code=exited, status=1/FAILURE)

juil. 03 13:06:07 pc2.home systemd[1]: Started hypergit-service.
juil. 03 13:06:08 pc2.home systemd[1]: hypergit-service.service: Main process exited, code=exited, status=1/FAILURE
juil. 03 13:06:08 pc2.home systemd[1]: hypergit-service.service: Failed with result 'exit-code'.
[mh-cbon@pc2 ~] $ /home/mh-cbon/.nvm/versions/node/v10.4.0/bin/node /home/mh-cbon/.nvm/versions/node/v10.4.0/bin/hypergit-service seed
[2018-7-3 13:07:23] Running with CLI arguments: /home/mh-cbon/.nvm/versions/node/v10.4.0/bin/node /home/mh-cbon/.nvm/versions/node/v10.4.0/bin/hypergit-service seed
fs.js:145
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/mh-cbon/.local/state/hypergit-nodejs/log.txt'
    at Object.fs.openSync (fs.js:579:3)
    at Object.fs.writeFileSync (fs.js:1309:33)
    at Object.fs.appendFileSync (fs.js:1355:6)
    at Console.args [as log] (/home/mh-cbon/.nvm/versions/node/v10.4.0/lib/node_modules/hypergit-service/node_modules/console2file/lib/index.js:111:20)
    at fs.unlink (/home/mh-cbon/.nvm/versions/node/v10.4.0/lib/node_modules/hypergit-service/bin/cli.js:82:19)
    at FSReqWrap.oncomplete (fs.js:171:20)
[mh-cbon@pc2 ~] $ 
[mh-cbon@pc2 ~] $ npm info -g hypergit

hypergit@3.2.0 | non-commercial | deps: 13 | versions: 11
command line tool for hypergit
https://github.com/noffle/hypergit

bin: hypergit, git-remote-hypergit

dist
.tarball https://registry.npmjs.org/hypergit/-/hypergit-3.2.0.tgz
.shasum: 079ea1394ee8441d313d3b2f38e4b171660236f1
.integrity: sha512-315zLxRlQFGeOFExIESnL2Cv/b+WDdtoC8EBfNWUxND4mTta8xklewInZbQu/azg2t+yjihVnmRF4C74g0/oHQ==
.unpackedSize: 15.1 kB

dependencies:
dat-swarm-defaults: ^1.0.1  git-remote-hypergit: ^2.0.1 hypercore-crypto: ^1.0.0    hyperdb: ^3.1.2             through2: ^2.0.3            
discovery-swarm: ^5.1.1     gitconfiglocal: ^2.0.1      hypercore: ^6.15.0          minimist: ^1.2.0            
env-paths: ^1.0.0           gitverse: ^1.0.0            hyperdb-git-repo: ^1.0.2    mkdirp: ^0.5.1              

maintainers:
- noffle <stephen.whitmore@gmail.com>

dist-tags:
latest: 3.2.0  

published 2 days ago by noffle <stephen.whitmore@gmail.com>
[mh-cbon@pc2 ~] $ npm info -g hypergit-service

hypergit-service@0.0.1 | MIT | deps: 7 | versions: 1
Runs hypergit seed as a background service
https://github.com/wmhilton/hypergit-service#readme

bin: hypergit-service

dist
.tarball https://registry.npmjs.org/hypergit-service/-/hypergit-service-0.0.1.tgz
.shasum: 774f71a6f4acee515892972c0b36db85ebaf65dd
.integrity: sha512-4YVDiPmugtpu1N26oZQ14hRn/2CLsObV6qGyeZR5cJ7wQPR0lAr5orY2lKadPX4MBEyFDqUP3/OuSRMZNW9zMA==
.unpackedSize: 5.6 kB

dependencies:
command-join: ^2.0.0 console2file: ^1.1.5 env-paths: ^1.0.0    is-elevated: ^2.0.1  minimisted: ^2.0.0   os-service: ^2.1.3   sudo-prompt: ^8.2.0  

maintainers:
- wmhilton <wmhilton@gmail.com>

dist-tags:
latest: 0.0.1  

published 2 days ago by wmhilton <wmhilton@gmail.com>
[mh-cbon@pc2 ~] $ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 28 (Twenty Eight)
Release:	28
Codename:	TwentyEight
[mh-cbon@pc2 ~] $ nvm --version
0.33.1
[mh-cbon@pc2 ~] $ npm --version
6.1.0
[mh-cbon@pc2 ~] $ node -v
v10.4.0
```

besides, i m up!

**Comment by billiegoose** [comment]
> besides, i m up!

Yay! Congrats. It is tricky stuff!

> mkdir -p

Ah... yep I can add that. **Edit: included in version 0.0.2**

> for now i worked around by forcing user/group into the service definition.

Awesome! Please consider making a PR to `os-service`. I think it would be a small addition to this file: https://github.com/nospaceships/node-os-service/blob/master/index.js  `os-service` has a username option for Windows, but it is currently ignored on Linux.

**Comment by mh-cbon** [comment]
reading at your code, i see you sudo everywhere https://github.com/wmhilton/hypergit-service/blob/master/bin/cli.js, except for the seed action!

The example available in os-service repository does not do so. Have you considered to run as current user ? Have you tried it ? https://github.com/nospaceships/node-os-service/blob/master/example/periodic-logger.js

**Comment by billiegoose** [comment]
I do run it as the current user, and recommend it. The `os-service` installer doesn't have a way to set the user for Linux though. Which is why I suggested you add that ability to os-service.
